In [1]:
import  numpy as np 

## **list vs numpy - time taken

In [3]:
from time import process_time

#### **time taken by a list 

In [4]:
python_list =[i for i in range(10000)]


start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print("Time taken to add 5 to each element in the list: ", end_time - start_time)

Time taken to add 5 to each element in the list:  0.0


In [6]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array +=5
end_time -start_time

-0.203125

### **numpy array

In [7]:
#list 
list = [1,2,3,4,5]
list
type(list)

list

In [8]:
np_array = np.array([1,2,3,4,5])
np_array
type(np_array)

numpy.ndarray

In [9]:
#creating a 1 d array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
a.shape

(5,)

In [13]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
b.shape

(2, 5)

In [16]:
c = np.array([(1,2,3,4,5),(6,7,8,9,10)],dtype = float)
c

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

### **initial placeholders in numpy arrays

In [17]:
# create a numpy array of zeros 
x = np.zeros((4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
# create a numpy array of ones
x = np.ones((4,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# create an identity matrix
a = np.eye(2,2)
a

array([[1., 0.],
       [0., 1.]])